### ISSUE TITLE
Compass with sodaq explorer

### ISSUE THREAD

**Issue by DenniZr** [janvl1234/Sodaq_NBIoT_examples#5]
If you like, i made a library for the sodaq explorer with nbiot shield for the compass. The Y and Z axes works, something wrong with the X axes. But it gives out an accurate heading in degrees.
https://github.com/DenniZr/sodaq-explorer-nbiot-compass

**Comment by janvl1234** [comment]
You made a nice library for to use the sodaq explorer + nbiot shield as a compass.
Feel free to make a post on forum.sodaq.com to show your library and to help others who are searching for this solution.
